# For authentication, paste a session cookie from your browser here, in single quotes
session-cookie: ''
download-location: /home/brian/hbd2/test/
chunk-size: 8192000
force_md5: False
write_md5: True
read_md5: True
debug: False
get_extra_file_info: False

default_headers:
  Accept: application/json
  Accept-Charset: utf-8
  Keep-Alive: True
  X-Requested-By: hb_android_app
  User-Agent: Apache-HttpClient/UNAVAILABLE (java 1.4)

default_params:
  ajax: True

download-platforms:
  audio: True
  ebook: True
  windows: True
  mac: True
  linux: True
  android: True
  asmjs: False

audio_types:
  flac: True
  ogg: True
  mp3: True
  other: True

ebook_types:
  epub: True
  pdf: True
  mobi: True
  other: True
